### ISSUE TITLE
feature request: Add a setting to embed .cab file into the .msi file

### ISSUE THREAD

**Issue by flyingxu** [tom-englert/Wax#1]
I would say that should be the default setting and Wax should make it easy.

**Comment by tom-englert** [comment]
As you may have noticed Wax currently only manages files, not properties.

To have defaults is so easy with WiX - just build a template with your preferences and include it - so I wonder if it's worth building a UI for this, since there are only very few properties for which this would  make sense.

Any suggestions how this could be handled?

**Comment by tom-englert** [comment]
@flyingxu If you think this should be the default setting for WiX, you should post a feature request here: https://github.com/wixtoolset/issues, not give a bad rating for a tool with a totally different scope.

**Comment by tom-englert** [comment]
This feature is not really in the scope of Wax.
