### ISSUE TITLE
Problem setting  root directory with Wix Setup editor

### ISSUE THREAD

**Issue by RobertOwenJack** [tom-englert/Wax#12]
When I create a WiX merge module project and attempt to use the WiX setup editor to configure it, the root directory is "MergeRedirectFolder" in the initial wxs file, and the editor will not recognise this as a root directory. A red warning icon is next to the Root Directory entry, and this prevents me from setting anything else up with the editor.  I am presuming that Wax can be used to configure merge module Wix projects?

**Comment by tom-englert** [comment]
No, I never have tried it with a merge module. The problem seems to be the special "MergeRedirectFolder" does not have a name attribute. Wax ignores directory entries without name, since in a regular setup project you always have an explicit directory where you want to install. I'll see if this restriction can be relaxed so it also works with merge modules.

As a workaround you could add a temporary name to the "MergeRedirectFolder" and then remove it after editing.

**Comment by RobertOwenJack** [comment]
Hi Tom
Thanks for the quick reply. I tried the same thing with Setup Library project and I had the same problem, but from what you have said that is to be expected as in a blank wix library project there are no directory entries at all.

I’d be really interested in seeing restrictions lifted – Wax takes the heavy lifting out of Wix, and quite apart from that is excellent way of learning how to do things in Wix.

Best regards

Robert

**Comment by RobertOwenJack** [comment]
Thanks Tom

**Comment by RobertOwenJack** [comment]
Hi Tom

I've noticed that the latest Wax releases no longer seem to work under VS2010 - the extension manifests have changed and it appears that VS2010 is no longer supported. Is there anyway to get the latest Wax versions to work with VS2010?

Best regards

Robert

**Comment by tom-englert** [comment]
Hi Robert,

I had to drop this since 2010 does not support the V2.0 manifests, but this is required to support VS2017.
However I think it should work if you build your own version with the latest sources; just rollback the .vsixmanifest to make it work with 2010 again.

**Comment by RobertOwenJack** [comment]
Thanks Tom
