### ISSUE TITLE
Editor does not close with solution is closed

### ISSUE THREAD

**Issue by mwpowellhtx** [tom-englert/Wax#7]
Editor does not close with solution is closed. It remains open.

**Comment by tom-englert** [comment]
Yes, this is intended. 
It shows information about all open projects. 
If no project is open, it just shows an empty list.

**Comment by mwpowellhtx** [comment]
User experience says that this is unexpected. When the project for which files is closed then the document window, in this case editor, should also close.

**Comment by tom-englert** [comment]
Yes, but this is neither a document window nor an editor window. 
It's a tool window like Output or Error List, they also don't disappear when you close the solution, only the respective content disappears.
I think your expectation is a modal dialog rather than a tool window, however I found a tool window more convenient.

**Comment by mwpowellhtx** [comment]
No, the classic "editor" is the textual one. But it's still a document window at its heart.

That said, I'll take it under consideration deciding how/whether to use WiX for my installer needs.
